server:
  port: 8080

spring:
  profiles:
    active: "dev"
  application:
    name: record-shop-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    kubernetes:
      discovery:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
    hostname: record-shop-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 1000
eureka:
  client:
    enabled: false
    service-url:
      registerWithEureka: false